version: "3.9"

services:
  db:
    image: mariadb:11.3
    container_name: theorganizer_db
    restart: unless-stopped

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    environment:
      MARIADB_DATABASE: theorganizer
      MARIADB_USER: theorganizer
      MARIADB_PASSWORD: devops
      MARIADB_ROOT_PASSWORD: rootpassword

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - theorganizer_net

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: theorganizer_app
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DB_HOST: db
      DB_USER: theorganizer
      DB_PASSWORD: devops
      DB_NAME: theorganizer

    depends_on:
      db:
        condition: service_healthy

    networks:
      - theorganizer_net

volumes:
  db_data:

networks:
  theorganizer_net:
